---
version: "2.1"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${USERDIR}/docker/homeass/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host  

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ${USERDIR}/docker/qbittorrent/config:/config
      - ${USERDIR}/docker/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped  

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${USERDIR}/docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
      - PLEX_CLAIM=claim-<your-string>
      - HOSTNAME=”PlexServer”
    volumes:
      - ${USERDIR}/docker/plex/config:/config
      - ${USERDIR}/docker/plex/transcodes:/transcode
      - ${USERDIR}/docker/plex/media:/media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${USERDIR}/docker/radarr/config:/config
    ports:
      - 7878:7878
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ${USERDIR}/docker/prometheus/etc:/etc/prometheus/
      - ${USERDIR}/docker/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: '1000'
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - ${USERDIR}/docker/grafana/data:/var/lib/grafana
      - ${USERDIR}/docker/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
        - ${USERDIR}/docker/portainer/data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
