---
version: "3.3"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    user: '0'
    volumes:
      - /home/barophobia/docker/homeass/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host  

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: '0'
    volumes:
      - /home/barophobia/docker/prometheus/etc:/etc/prometheus/
      - /home/barophobia/docker/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    user: '0'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: '0'
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - /home/barophobia/docker/grafana/data:/var/lib/grafana
      - /home/barophobia/docker/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000