---
version: "3.3"

services:  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /mnt/hd/docker/qbittorrent/config:/config
      - /mnt/hd/Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped  

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /mnt/hd/docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - HOSTNAME=”PlexServer”
    volumes:
      - /mnt/hd/docker/plex/config:/config
      - /mnt/hd/docker/plex/transcodes:/transcode
      - /mnt/hd/docker/plex/media:/media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /mnt/hd/docker/radarr/config:/config
      - /mnt/hd/Movies:/movies
      - /mnt/hd/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /mnt/hd/docker/sonarr/config:/config
      - /mnt/hd/tv:/tv #optional
      - /mnt/hd/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped