---
version: "2.1"

services:  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /home/barophobia/docker/qbittorrent/config:/config
      - /home/barophobia/docker/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped  

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/barophobia/docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
      - PLEX_CLAIM=claim-<your-string>
      - HOSTNAME=”PlexServer”
    volumes:
      - /home/barophobia/docker/plex/config:/config
      - /home/barophobia/docker/plex/transcodes:/transcode
      - /home/barophobia/docker/plex/media:/media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/barophobia/docker/radarr/config:/config
    ports:
      - 7878:7878
    restart: unless-stopped