---
version: "2.1"

volumes:
  qbittorrentConfig:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.160,rw"
      device: ":/mnt/media/qbittorrent/config"
  qbittorrentDownloads:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.160,rw"
      device: ":/mnt/media/qbittorrent/downloads"
  plexMovies:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.160,rw"
      device: ":/mnt/media/movies"
  plexTV:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.160,rw"
      device: ":/mnt/media/tvshows"
  sonarrConfig:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.160,rw"
      device: ":/mnt/media/sonarr/config"
  radarrConfig:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.160,rw"
      device: ":/mnt/media/radarr/config"
  jackettConfig:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.160,rw"
      device: ":/mnt/media/jackett/config"

services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - jackettConfig:/config
      - qbittorrentDownloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - radarrConfig:/config
      - plexMovies:/movies
      - qbittorrentDownloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - sonarrConfig:/config
      - plexTV:/tv
      - qbittorrentDownloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      -  qbittorrentConfig:/config
      -  qbittorrentDownloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped