#Change this hosts variable to the required host in your hosts.ini file.
- hosts: gameserver

  tasks:
  
  - name: Update all packages to latest
    apt:
      name: "*"
      state: latest

  - name: Dist upgrade
    apt:
      upgrade: dist

  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'nfs-common']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Install Docker Module for Python
    pip:
      name: docker-compose

  - name: Make sure docker is started
    service:
      name: docker
      state: started
      enabled: yes

  - name: Remove "apparmor" package
    apt:
      name: apparmor
      state: absent

  - name: copy Docker Compose files
    copy:
      src: "../docker/game-compose.yml"
      dest: ~/

  - name: deploy Docker Compose stack
    docker_compose:
      project_src: ~/
      files: game-compose.yml
      state: present
